### PR TITLE
Feature/composer update

### PR DESCRIPTION
**Pull request by lukewhitmore**
Updated contrib modules / Drupal core to 8.4.4. Also added Drupal console / admin toolbar.

https://github.com/wellcometrust/upd/issues/220

### CODE REVIEW

**Comment by amneale** [comment]
Should `/vendor` be gitignored? Quite hard to look over the diff otherwise!

**Comment by lukewhitmore** [comment]
I'd usually ignore vendor completely, and build using composer on the target system. Currently understand that UPD has been setup this way to ease CI deployment.

Conventionally, would bring in core, contrib and custom modules housed on github via composer on target platform.

Happy to investigate more conventional approach. Biggest risk with current setup is disparity between development environment and staging / prod; composer could include platform specific dependencies that conflict with target staging / production environments.

@alfraser86 Could you provide any steer?

**Comment by annikaC** [comment]
We've used composer_manager with D7 before to build on our target envs. D8 should make this a lot easier though. We have build scripts that would need adjusting, not sure how they work for this site though - @alfraser86 ?

**Comment by annikaC** [comment]
I guess we should get this merged so the other PRs can get reviewed!

**Pull request merged**
